#!/usr/bin/env node
/*
 * Tier 2 deterministic verdict/issue parser for triad-all / triad-codex.
 *
 * Turns a lens output file into validated structured JSON so synthesis works on
 * RECORDS, not raw prose. Code extracts; the LLM does cross-model triage.
 * Self-contained, no deps, never throws.
 *
 * Output (stdout): {"lens","verdict","degraded":bool,"skipped":N,"overflow":N,
 *                   "blocks":N,"issues":[{severity,locus,text}],"questions":[..]}
 *
 * Contract (mirrors SKILL.md "출력 파서 v1"):
 *  - Fence tokens matched LINE-ANCHORED; zero-width chars stripped ONLY for the
 *    token comparison (issue/question CONTENT preserved byte-for-byte).
 *  - Scan ALL fenced blocks, pick the one with the strongest signal
 *    (has-verdict dominant, then #issues+#questions); ties -> first. Survives
 *    Codex doubling AND an example/format fence emitted before the real answer.
 *  - VERDICT | PASS|REVISE|BLOCK (first wins).
 *    ISSUE | <sev> | LOCUS | TEXT  -- sev normalized (high/major, med/medium/
 *    moderate, low/minor/nit/info, crit/critical) ; LOCUS non-empty pipe-free,
 *    TEXT non-empty. QUESTION | TEXT. Leading list/quote marker ("- ","1. ")
 *    stripped. Anything else skipped + counted. issues/questions capped.
 *  - No verdict in any block -> DEGRADED, but ALREADY-PARSED issues/questions are
 *    PRESERVED (a marker is prepended, never replaces them) -- never silent-drop.
 *
 * Usage: node parse-triad.js <file> <lens>   |   node parse-triad.js --selftest
 *
 * SINGLE-SOURCED: canonical = triad-all/parse-triad.js; triad-codex's copy is
 * generated by skills/sync-review-parsers.sh. Edit ONLY the canonical, then sync.
 * Created by: Minwoo Park
 */
'use strict';
const fs = require('fs');

const BEGIN = '<<<TRIAD-FINDINGS v1>>>';
const END = '<<<END>>>';
const MAX = 200;
// constructed via strings so the source contains NO literal line/zero-width chars
const NL = new RegExp('\\r\\n|\\n|\\r|\\u2028|\\u2029');
const ZW = new RegExp('[\\u200B-\\u200F\\u202A-\\u202E\\u2060-\\u2064\\uFEFF\\u00AD]', 'g');
const LIST_PREFIX = /^(?:[-*>•]\s+|\d+[.)]\s+)?/;
const VERDICT_RE = /^VERDICT\s*\|\s*(PASS|REVISE|BLOCK)\b/i;
const ISSUE_RE = /^ISSUE\s*\|\s*([A-Za-z]+)\s*\|\s*([^|]+?)\s*\|\s*(\S.*)$/i;
const QUESTION_RE = /^QUESTION\s*\|\s*(\S.*)$/i;
const SEV_MAP = {
  CRIT: 'high', CRITICAL: 'high', BLOCKER: 'high', HIGH: 'high', MAJOR: 'high',
  MED: 'med', MEDIUM: 'med', MODERATE: 'med', WARN: 'med', WARNING: 'med',
  LOW: 'low', MINOR: 'low', NIT: 'low', INFO: 'low', TRIVIAL: 'low',
};
const tok = (s) => s.replace(ZW, '').trim();

function parseBody(bodyLines) {
  let verdict = null;
  const issues = [], questions = [];
  let skipped = 0, overflow = 0;
  for (const raw of bodyLines) {
    const t = raw.trim();
    if (!t) continue;
    const s = t.replace(LIST_PREFIX, '');
    let m;
    if ((m = s.match(VERDICT_RE))) {
      if (verdict === null) verdict = m[1].toUpperCase();
    } else if ((m = s.match(ISSUE_RE))) {
      const sev = SEV_MAP[m[1].toUpperCase()];
      const locus = m[2].trim(), text = m[3].trim();
      if (!sev || !locus || !text) { skipped++; continue; }
      if (issues.length >= MAX) { overflow++; continue; }
      issues.push({ severity: sev, locus, text });
    } else if ((m = s.match(QUESTION_RE))) {
      if (questions.length >= MAX) { overflow++; continue; }
      questions.push(m[1].trim());
    } else {
      skipped++;
    }
  }
  return { verdict, issues, questions, skipped, overflow };
}

function parse(text, lens) {
  lens = lens || 'unknown';
  text = typeof text === 'string' ? text : String(text == null ? '' : text);
  const lines = text.split(NL);

  const blocks = [];
  let cur = null;
  for (const ln of lines) {
    const t = tok(ln);
    if (t === BEGIN) { cur = []; blocks.push(cur); continue; }
    if (t === END) { cur = null; continue; }
    if (cur) cur.push(ln);
  }

  // strongest block: verdict dominant, then issue+question count; ties -> first
  let best = null, bestScore = -1;
  for (const b of blocks) {
    const p = parseBody(b);
    const score = (p.verdict ? 1000 : 0) + p.issues.length + p.questions.length;
    if (score > bestScore) { bestScore = score; best = p; }
  }
  if (!best) best = { verdict: null, issues: [], questions: [], skipped: 0, overflow: 0 };

  if (best.verdict === null) {
    const marker = {
      severity: 'med', locus: lens,
      text: blocks.length
        ? 'DEGRADED: fence(s) present but no VERDICT -> inspect raw or re-run'
        : 'DEGRADED: no v1 fence found -> inspect raw or re-run'
    };
    return {
      lens, verdict: 'DEGRADED', degraded: true, skipped: best.skipped, overflow: best.overflow,
      blocks: blocks.length, issues: [marker, ...best.issues], questions: best.questions,  // preserve, never replace
    };
  }
  return {
    lens, verdict: best.verdict, degraded: false, skipped: best.skipped, overflow: best.overflow,
    blocks: blocks.length, issues: best.issues, questions: best.questions,
  };
}

function selftest() {
  let n = 0, fails = 0;
  const t = (name, cond) => { n++; if (!cond) { console.error('FAIL:', name); fails++; } else console.log('ok  :', name); };
  const ZWS = String.fromCharCode(0x200B);

  let r = parse('reason\n<<<TRIAD-FINDINGS v1>>>\nVERDICT | REVISE\nISSUE | high | auth.py:10 | leak -> close\nQUESTION | is X intended?\n<<<END>>>', 'architect');
  t('clean: REVISE + issue + question', r.verdict === 'REVISE' && !r.degraded && r.issues.length === 1 && r.questions.length === 1);

  r = parse('<<<TRIAD-FINDINGS v1>>>\nVERDICT | PASS\n<<<END>>>\ntokens used\n<<<TRIAD-FINDINGS v1>>>\nVERDICT | PASS\n<<<END>>>', 'llm');
  t('doubled identical: PASS, blocks=2', r.verdict === 'PASS' && r.blocks === 2);

  // idx0: example/stub fence first (VERDICT|PASS, 0 issues), real block second (BLOCK + issues) -> pick real
  r = parse('Format I will use:\n<<<TRIAD-FINDINGS v1>>>\nVERDICT | PASS\n<<<END>>>\nMy real review:\n<<<TRIAD-FINDINGS v1>>>\nVERDICT | BLOCK\nISSUE | high | real.py | real bug -> fix\n<<<END>>>', 'llm');
  t('idx0: picks the real (richer) block, BLOCK not PASS', r.verdict === 'BLOCK' && r.issues.length === 1);

  // idx1: severity aliases normalized, not dropped
  r = parse('<<<TRIAD-FINDINGS v1>>>\nVERDICT | BLOCK\nISSUE | critical | a | sqli -> param\nISSUE | medium | b | perf -> cache\n<<<END>>>', 'x');
  t('idx1: critical->high, medium->med (none dropped)', r.issues.length === 2 && r.issues[0].severity === 'high' && r.issues[1].severity === 'med');

  // idx6: fence present, NO verdict, but real issues parsed -> DEGRADED yet issues PRESERVED
  r = parse('<<<TRIAD-FINDINGS v1>>>\nISSUE | high | crit.py | real bug 1 -> fix\nISSUE | med | x.py | bug 2 -> fix\n<<<END>>>', 'architect');
  t('idx6: no-verdict degraded but issues preserved (marker + 2 real)', r.degraded === true && r.issues.length === 3 && r.issues[1].locus === 'crit.py');

  r = parse('I will emit <<<TRIAD-FINDINGS v1>>> later.\n<<<TRIAD-FINDINGS v1>>>\nVERDICT | BLOCK\n<<<END>>>', 'x');
  t('prose-quote ignored (BLOCK)', r.verdict === 'BLOCK');

  r = parse('<<<TRIAD-FINDINGS v1>>>\nVERDICT | REVISE\nISSUE | low | p | mentions <<<END>>> inline -> ok\nISSUE | med | q | survives -> ok\n<<<END>>>', 'x');
  t('END-in-text: both issues survive', r.issues.length === 2);

  r = parse('prose, no fence', 'x');
  t('no fence: degraded', r.degraded === true && /no v1 fence/.test(r.issues[0].text));

  r = parse('<<<TRIAD-FINDINGS v1>>>\nVERDICT | REVISE\nISSUE | high | a' + ZWS + 'b | keep' + ZWS + 'zw -> fix\n<<<END>>>', 'x');
  t('content ZW preserved', r.issues.length === 1 && r.issues[0].locus.indexOf(ZWS) !== -1);

  let threw = false;
  try { parse(undefined); parse(null); parse(7); } catch (_) { threw = true; }
  t('never throws on non-string', !threw);

  console.log(fails ? `\n${fails}/${n} FAILED` : `\nALL PASS (${n}/${n})`);
  process.exit(fails ? 1 : 0);
}

const args = process.argv.slice(2);
if (args[0] === '--selftest') {
  selftest();
} else {
  const file = args[0];
  const lens = args[1] || 'unknown';
  let text = '';
  try { text = fs.readFileSync(file, 'utf8'); } catch (_) { text = ''; }
  process.stdout.write(JSON.stringify(parse(text, lens)));
}
